# Generated by Django 4.2 on 2025-06-21 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('descriptions', models.TextField(max_length=3500)),
                ('email', models.CharField(max_length=75)),
                ('phone', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=120)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instgram', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
