# Generated by Django 4.2 on 2025-06-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default='', upload_to='photo_commpany'),
            preserve_default=False,
        ),
    ]
