# Generated by Django 4.2 on 2025-06-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_applyuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyuser',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
            preserve_default=False,
        ),
    ]
